apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: embarkx/tax-service-b
      #    env:
        #  - name: ENV_VALUE
       #     value: "Hello from app.yaml"
        #  - name: DB_PASSWORD
       #     value: "CGFzc3dwcmQ="
          ports:
          - containerPort: 4000    
         # env:
         #   - name: APP_MESSAGE
          #    valueFrom:
           #     configMapKeyRef:
            #      name: app-config
             #     key: APP_MESSAGE
           # - name: DB_PASSWORD
            #  valueFrom:
             #   secretKeyRef:
              #    name: db-secret
               #   key: DB_PASSWORD